language: cpp
os: linux
dist: bionic

addons:
  apt:
    packages:
      - g++-8
      - clang++-8
      - clang-tidy-9
      - libbenchmark-dev
      - libboost-stacktrace-dev
      - cmake

env:
  - BMI2_CMD="-DUSE_BMI2=OFF" MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
  - BMI2_CMD="-DUSE_BMI2=ON" MATRIX_EVAL="export CC=gcc-8 && export CXX=g++-8"
  - BMI2_CMD="-DUSE_BMI2=OFF" MATRIX_EVAL="export CC=clang-8 && export CXX=clang++-8"
  - BMI2_CMD="-DUSE_BMI2=ON" MATRIX_EVAL="export CC=clang-8 && export CXX=clang++-8"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - git clone --branch release-1.10.0 https://github.com/google/googletest/
  - mkdir googletest/prefix
  - ( cd googletest && cmake . && make -j2 && make DESTDIR=prefix install )
  - export GTEST_ROOT="$PWD/googletest/prefix/usr/local"

before_script:
  - mkdir build build_dgn

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ${BMI2_CMD} -DUSE_NO_EXCEPTIONS=ON -DCMAKE_CXX_CLANG_TIDY='clang-tidy-9;--warnings-as-errors=*' ..
  - make -j2
  - ctest
  - cd ../build_dgn
  - cmake -DCMAKE_BUILD_TYPE=Release ${BMI2_CMD} -DUSE_NO_EXCEPTIONS=ON -DUSE_SEARCH_DIAGNOSTICS=ON ..
  - make -j2
  - ctest -R '^smoke$'
